### ISSUE TITLE
Suggestion to add more exchanges

### ISSUE THREAD

**Issue by AhmedSakrr** [lbkolev/arbitrage-gossip#2]
please add KuCoin and more exchanges .. thanks in advance and great job.

**Comment by lbkolev** [comment]
Added KuCoin,

Will add some more in the future.

**Comment by AhmedSakrr** [comment]
Nice thanks bittrex.com is good too Centralized exchanges.. in addition to, DEXs decentralized exchanges like uniswap .. sushiswap  1inch.. pankcakeswap etc.. are Perfect.
